### ISSUE TITLE
When renaming new image I get error below: 

### ISSUE THREAD

**Issue by ericlikedis** [Loiuy123/Tartarus#2]
```
Traceback (most recent call last):
  File "/Users/<username>/Tartarus/tartarus/tartarus.py", line 584, in <module>
    image_encode()
  File "/Users/<username>/Tartarus/tartarus/tartarus.py", line 533, in image_encode
    newimg.save(new_img_name, str(new_img_name.split(".")[1].upper()))
IndexError: list index out of range
```

**Comment by pantsman0** [comment]
Does the new image name have a dot in it?

**Comment by ericlikedis** [comment]
Rookie mistake...I got it now lol..
